# Generated by Django 5.2 on 2026-05-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Fallback if no first/last name', max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('gmail', 'Gmail'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('phone', 'Phone / vCard'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20)),
                ('source_id', models.CharField(blank=True, help_text='External ID for deduplication', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='contacts', to='projects.project')),
                ('tasks', models.ManyToManyField(blank=True, related_name='contacts', to='projects.task')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'display_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_id', ''), _negated=True), fields=('source', 'source_id'), name='contacts_unique_source_id')],
            },
        ),
    ]
