# Generated by Django 5.2 on 2026-07-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('score', models.PositiveIntegerField()),
                ('era_reached', models.CharField(blank=True, default='', max_length=60)),
                ('waves_cleared', models.PositiveSmallIntegerField(default=0)),
                ('victory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score', 'created_at'],
                'indexes': [models.Index(fields=['-score'], name='math_bastio_score_58502d_idx')],
            },
        ),
    ]
