# Generated by Django 5.2 on 2026-07-19 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_bastion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=140)),
                ('gems', models.PositiveIntegerField()),
                ('bonus_gems', models.PositiveIntegerField(default=0)),
                ('price_cents', models.PositiveIntegerField(help_text='USD cents; display only until a provider is configured.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'price_cents'],
            },
        ),
        migrations.CreateModel(
            name='PlayerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gems', models.PositiveIntegerField(default=0)),
                ('lifetime_gems_purchased', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('provider', models.CharField(choices=[('none', 'Not configured'), ('stripe', 'Stripe'), ('apple', 'Apple App Store'), ('google', 'Google Play')], default='none', max_length=12)),
                ('provider_ref', models.CharField(blank=True, default='', help_text='Provider-side id: Stripe session, Apple/Google transaction id.', max_length=200)),
                ('price_cents', models.PositiveIntegerField()),
                ('gems_granted', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='math_bastion.gemproduct')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='math_bastion.playerwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
