# Generated by Django 5.2 on 2026-01-09 00:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('total_score', models.IntegerField(default=0)),
                ('total_rounds', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('training_mode', models.BooleanField(default=False, help_text='Hint costs points in training mode')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('scenario_title', models.CharField(max_length=200)),
                ('transcript', models.JSONField(help_text='List of dialogue lines')),
                ('correct_type', models.CharField(choices=[('driver', 'Driver'), ('expressive', 'Expressive'), ('relational', 'Relational'), ('analyzer', 'Analyzer'), ('free_spirit', 'Free Spirit'), ('guardian', 'Guardian')], max_length=20)),
                ('tell_category', models.CharField(choices=[('control', 'Control'), ('visibility', 'Visibility'), ('belonging', 'Belonging'), ('accuracy', 'Accuracy'), ('freedom', 'Freedom'), ('safety', 'Safety')], max_length=20)),
                ('tell_explanation', models.TextField(help_text='Explanation of the tell(s) in the transcript')),
                ('response_choices', models.JSONField(help_text='Dict with keys A, B, C, D mapping to response text')),
                ('correct_response', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('response_explanation', models.TextField(help_text='Why this response is correct')),
                ('is_feels_unheard', models.BooleanField(default=False, help_text='Variant where person feels unheard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'id'],
                'indexes': [models.Index(fields=['difficulty', 'correct_type'], name='personality_difficu_7f5961_idx'), models.Index(fields=['correct_type'], name='personality_correct_6875e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('player_type_guess', models.CharField(blank=True, choices=[('driver', 'Driver'), ('expressive', 'Expressive'), ('relational', 'Relational'), ('analyzer', 'Analyzer'), ('free_spirit', 'Free Spirit'), ('guardian', 'Guardian')], max_length=20, null=True)),
                ('player_response_choice', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('player_tell_category', models.CharField(blank=True, choices=[('control', 'Control'), ('visibility', 'Visibility'), ('belonging', 'Belonging'), ('accuracy', 'Accuracy'), ('freedom', 'Freedom'), ('safety', 'Safety')], max_length=20, null=True)),
                ('type_correct', models.BooleanField(default=False)),
                ('response_correct', models.BooleanField(default=False)),
                ('tell_correct', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('hint_used', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality_type_game.gamesession')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality_type_game.scenario')),
            ],
            options={
                'ordering': ['session', 'round_number'],
                'unique_together': {('session', 'round_number')},
            },
        ),
    ]
