# Generated by Django 5.2 on 2026-01-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_type_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('relationship', 'Relationship/Romantic')], default='business', max_length=20),
        ),
        migrations.AddField(
            model_name='scenario',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('relationship', 'Relationship/Romantic')], default='business', max_length=20),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['category', 'difficulty', 'correct_type'], name='personality_categor_e4a9f3_idx'),
        ),
    ]
