# Generated by Django 5.2 on 2025-12-05 01:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('coverage_radius', models.FloatField(default=50.0)),
                ('occupancy', models.IntegerField(default=0)),
                ('parking_lot_size', models.FloatField(default=0.0)),
                ('acreage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('inactive', 'Inactive')], default='proposed', max_length=20)),
                ('points_covered', models.IntegerField(default=0)),
                ('total_risk_covered', models.FloatField(default=0.0)),
                ('total_population_covered', models.IntegerField(default=0)),
                ('avg_drive_time', models.FloatField(default=0.0)),
                ('max_drive_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'POD',
                'verbose_name_plural': 'PODs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('general', 'General'), ('pandemic', 'Pandemic'), ('natural_disaster', 'Natural Disaster'), ('severe_weather', 'Severe Weather'), ('infrastructure_failure', 'Infrastructure Failure')], default='general', max_length=30)),
                ('severity', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)])),
                ('affected_areas', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioPOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency_preparedness.pod')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency_preparedness.scenario')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('scenario', 'pod')},
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='pods',
            field=models.ManyToManyField(related_name='scenarios', through='emergency_preparedness.ScenarioPOD', to='emergency_preparedness.pod'),
        ),
    ]
