# Generated by Django 6.0.3 on 2026-03-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='facets',
            field=models.ManyToManyField(blank=True, related_name='publications', to='mdh_publications.facet'),
        ),
        migrations.AlterField(
            model_name='topicgroup',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
