# Generated by Django 6.0.3 on 2026-04-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_publications', '0003_landingimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingimage',
            options={'ordering': ['slot', 'sort_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='landingimage',
            name='slot',
            field=models.CharField(choices=[('hero', 'Hero Carousel'), ('browse_topic', 'Browse by Topic Card'), ('browse_contributor', 'Browse by Contributor Card'), ('browse_format', 'Browse by Format Card')], default='hero', help_text='Where this image is displayed on the landing page.', max_length=30),
        ),
    ]
