# Generated by Django 6.0.3 on 2026-04-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_publications', '0004_alter_landingimage_options_landingimage_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pdf_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
