# Generated by Django 5.2 on 2026-08-19 15:07

import django.core.validators
from django.db import migrations, models


def copy_summary_abstract_into_description(apps, schema_editor):
    Publication = apps.get_model("mdh_publications", "Publication")
    for publication in Publication.objects.all():
        parts = []
        summary = (getattr(publication, "summary", None) or "").strip()
        abstract = (getattr(publication, "abstract", None) or "").strip()
        if summary:
            parts.append(summary)
        if abstract and abstract != summary:
            parts.append(abstract)
        description = "\n\n".join(parts)
        if description:
            publication.description = description
            publication.save(update_fields=["description"])


class Migration(migrations.Migration):

    dependencies = [
        ("mdh_publications", "0006_accessrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="scope_note",
            field=models.TextField(
                blank=True,
                help_text="Short controlled-vocabulary note describing when to use this type.",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Dublin Core description of the publication (minimum 150 characters on the upload form).",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="is_translated",
            field=models.BooleanField(
                default=False,
                help_text="Check if this file is a translation of another publication.",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("hmn", "Hmong"),
                    ("so", "Somali"),
                    ("ksw", "Karen"),
                    ("vi", "Vietnamese"),
                ],
                default="en",
                help_text="Language of this document, not the community it is about.",
                max_length=8,
            ),
        ),
        migrations.RunPython(copy_summary_abstract_into_description, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="publication",
            name="abstract",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="summary",
        ),
        migrations.AlterField(
            model_name="publication",
            name="file_upload",
            field=models.FileField(
                blank=True,
                help_text="Upload the document file. Accepted types: PDF, DOCX, XLSX, CSV, PPTX, PNG, JPG.",
                null=True,
                upload_to="mdh_publications/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "docx", "xlsx", "csv", "pptx", "png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Only library stewards should feature publications on the landing page.",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Canonical public page for this publication (for example on health.mn.gov).",
            ),
        ),
    ]
