# Generated by Django 5.2 on 2026-08-20 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_publications', '0007_publication_description_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('zh', 'Chinese (Simplified)'), ('prs', 'Dari'), ('gu', 'Gujarati'), ('hi', 'Hindi'), ('hmn', 'Hmong'), ('ksw', 'Karen'), ('km', 'Khmer'), ('ko', 'Korean'), ('lo', 'Lao'), ('ne', 'Nepali'), ('so', 'Somali'), ('ur', 'Urdu'), ('vi', 'Vietnamese')], default='en', help_text='Language of this document, not the community it is about.', max_length=8),
        ),
        migrations.CreateModel(
            name='TagConstellationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mdh_space', 'MDH Space / Product'), ('statute_policy', 'Related Statute / Policy'), ('resource_group', 'Resource / Group'), ('publication_ref', 'Publication')], max_length=32)),
                ('title', models.CharField(max_length=500)),
                ('note', models.TextField(blank=True, help_text='Optional citation detail, scope note, or steward comment.')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('publication', models.ForeignKey(blank=True, help_text='Optional link to a cataloged publication in this library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constellation_links', to='mdh_publications.publication')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constellation_items', to='mdh_publications.tag')),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'title'],
            },
        ),
    ]
