# Generated by Django 5.2 on 2026-03-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, help_text='e.g. +', max_length=20)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('year', models.PositiveIntegerField(help_text='Primary year for sorting (e.g. 2025)')),
                ('summary', models.TextField(help_text='Short description for cards and lists')),
                ('body', models.TextField(blank=True, help_text='Optional longer narrative')),
                ('location', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(blank=True, help_text='US state code if applicable', max_length=2)),
                ('featured', models.BooleanField(default=False)),
                ('raised_fists', models.PositiveIntegerField(default=0, help_text='Community acknowledgment count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collections', models.ManyToManyField(blank=True, related_name='events', to='nomoar.collection')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='nomoar.tag')),
            ],
            options={
                'verbose_name': 'Historical event',
                'verbose_name_plural': 'Historical events',
                'ordering': ['-year', '-created_at'],
                'indexes': [models.Index(fields=['-year', 'featured'], name='nomoar_hist_year_5a98c6_idx'), models.Index(fields=['slug'], name='nomoar_hist_slug_82224e_idx')],
            },
        ),
    ]
