# Generated by Django 5.2 on 2026-03-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevent',
            name='latitude',
            field=models.FloatField(blank=True, help_text='WGS84 latitude for map (e.g. 36.1)', null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='longitude',
            field=models.FloatField(blank=True, help_text='WGS84 longitude for map (e.g. -112.1)', null=True),
        ),
    ]
