# Generated by Django 5.2 on 2026-03-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoar', '0002_historicalevent_latitude_historicalevent_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevent',
            name='event_type',
            field=models.CharField(choices=[('violence', 'Violence'), ('policy', 'Policy'), ('legislation', 'Legislation'), ('discrimination', 'Discrimination')], db_index=True, default='policy', help_text='Category for map color and legend', max_length=32),
        ),
    ]
