# Generated by Django 5.2 on 2026-03-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoar', '0003_historicalevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Short role or descriptor under the name', max_length=300)),
                ('summary', models.TextField(help_text='Card text on the Heroes index')),
                ('body', models.TextField(blank=True, help_text='Longer biography on the detail page')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveIntegerField(blank=True, null=True)),
                ('portrait', models.ImageField(blank=True, help_text='Optional photo (upload in admin)', null=True, upload_to='nomoar/heroes/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Change maker / hero',
                'verbose_name_plural': 'Change makers & heroes',
                'ordering': ['order', 'name'],
            },
        ),
    ]
