# Generated by Django 5.2 on 2026-03-21 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoar', '0004_changemaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='changemaker',
            name='related_events',
            field=models.ManyToManyField(blank=True, help_text='Timeline entries to highlight on this profile', related_name='related_heroes', to='nomoar.historicalevent'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='editorial_note',
            field=models.TextField(blank=True, help_text='Optional note shown on the entry (e.g. review status)'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='last_reviewed',
            field=models.DateField(blank=True, help_text='Last editorial or fact-check review (optional)', null=True),
        ),
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('citation', models.CharField(blank=True, help_text='Publication, author, or short reference line', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='nomoar.historicalevent')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
