# Generated by Django 5.2 on 2026-03-21 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoar', '0005_eventsource_editorial_hero_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventThemeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(help_text='Shown on cards (lowercased in CSS)', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Theme label',
                'verbose_name_plural': 'Theme labels',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='EventFistVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fist_votes', to='nomoar.historicalevent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'session_key'), name='nomoar_eventfistvote_event_session_uniq')],
            },
        ),
    ]
