# Generated by Django 5.2 on 2026-03-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoar', '0006_theme_labels_fist_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevent',
            name='theme_labels',
            field=models.ManyToManyField(blank=True, help_text='Pills above the title (institutional, cultural, court case, …)', related_name='events', to='nomoar.eventthemelabel'),
        ),
    ]
