# Generated by Django 5.2 on 2026-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomoar', '0008_seed_event_theme_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevent',
            name='curated_related',
            field=models.ManyToManyField(blank=True, help_text='Manually curated related entries (shown first on the detail page).', related_name='related_from_curated', to='nomoar.historicalevent'),
        ),
    ]
