# Generated by Django 5.2 on 2026-03-21 20:10

import django.db.models.deletion
from django.db import migrations, models


def create_engagement_config(apps, schema_editor):
    EngagementConfig = apps.get_model('nomoar', 'EngagementConfig')
    EngagementConfig.objects.get_or_create(
        pk=1,
        defaults={
            'things_to_avoid_note': (
                'We do not run programmatic ads on sensitive historical entries, '
                'paywall the public record without a strong free tier, or accept '
                'pay-for-placement in search or “related events” without clear disclosure.'
            ),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('nomoar', '0009_curated_related_feeds_embed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_url', models.URLField(blank=True, help_text='Donate / fundraiser link')),
                ('membership_url', models.URLField(blank=True, help_text='Supporter or membership tiers')),
                ('institutional_contact_email', models.EmailField(blank=True, max_length=254)),
                ('api_partnerships_url', models.URLField(blank=True, help_text='API / data licensing info')),
                ('grants_fiscal_sponsorship_blurb', models.TextField(blank=True, help_text='Shown on Support page')),
                ('museum_services_blurb', models.TextField(blank=True, help_text='Custom ingest, white-label map/timeline, consulting')),
                ('sponsorship_policy', models.TextField(blank=True, help_text='Transparent sponsored collections; no pay-for-placement in search')),
                ('things_to_avoid_note', models.TextField(blank=True, help_text='e.g. no programmatic ads on sensitive entries')),
                ('merch_print_blurb', models.TextField(blank=True, help_text='Posters, maps, print-on-demand')),
            ],
            options={
                'verbose_name': 'Engagement & support settings',
                'verbose_name_plural': 'Engagement & support settings',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('intro', models.TextField(help_text='Introduction for classrooms / tours')),
                ('theme_place_decade_note', models.CharField(blank=True, help_text='Optional subtitle (e.g. “Minnesota · 1960s · Policy”)', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning path',
                'verbose_name_plural': 'Learning paths',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LocalizedResourcePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('county', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, help_text='US state code if applicable', max_length=2)),
                ('embed_slice_hint', models.TextField(blank=True, help_text='Query string tips for /Embed/slice/?state=MN&decade=1960s etc.')),
                ('printable_pdf', models.FileField(blank=True, null=True, upload_to='nomoar/packs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Localized resource pack',
                'verbose_name_plural': 'Localized resource packs',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, help_text='Internal', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter subscriber',
                'verbose_name_plural': 'Newsletter subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='changemaker',
            old_name='body',
            new_name='biography',
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='biography',
            field=models.TextField(
                blank=True,
                help_text='Full biography on the hero profile (below the summary)',
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='guest_byline',
            field=models.CharField(blank=True, help_text='e.g. “Guest introduction by …”', max_length=300),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_partner_spotlight',
            field=models.BooleanField(db_index=True, default=False, help_text='Highlight on educator / community pages'),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='partner_organization',
            field=models.CharField(blank=True, help_text='Library, museum, or org name for partner spotlight pages', max_length=200),
        ),
        migrations.AddField(
            model_name='collection',
            name='partner_url',
            field=models.URLField(blank=True, help_text='Partner website'),
        ),
        migrations.AddField(
            model_name='collection',
            name='sponsor_disclosure',
            field=models.TextField(blank=True, help_text='Transparent note if a collection is underwritten (does not affect search ranking)'),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='attachment',
            field=models.FileField(blank=True, help_text='PDF, image, or other file (optional)', null=True, upload_to='nomoar/sources/'),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='context_note',
            field=models.TextField(blank=True, help_text='Short classroom-facing context for this source'),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='media_embed_url',
            field=models.URLField(blank=True, help_text='Link to audio/video or embeddable resource (oral history, etc.)', max_length=500),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='source_kind',
            field=models.CharField(choices=[('link', 'Web link'), ('document', 'Uploaded document'), ('image', 'Image / scan'), ('av', 'Audio / video embed')], default='link', max_length=16),
        ),
        migrations.CreateModel(
            name='ArchiveNewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('teaser', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(db_index=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_events', models.ManyToManyField(blank=True, related_name='news_posts', to='nomoar.historicalevent')),
            ],
            options={
                'verbose_name': 'Archive commentary post',
                'verbose_name_plural': 'Archive commentary posts',
                'ordering': ['-published_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('definition', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('related_events', models.ManyToManyField(blank=True, related_name='glossary_terms', to='nomoar.historicalevent')),
            ],
            options={
                'verbose_name': 'Glossary term',
                'verbose_name_plural': 'Glossary terms',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LessonKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('standards_alignment', models.TextField(blank=True, help_text='Standards or competencies this kit supports')),
                ('discussion_prompts', models.TextField(blank=True)),
                ('map_timeline_activity', models.TextField(blank=True, help_text='Instructions using timeline, map, or embeddable widgets')),
                ('body', models.TextField(blank=True, help_text='Main lesson narrative / printable content')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='nomoar/lesson_kits/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_kits', to='nomoar.learningpath')),
            ],
            options={
                'verbose_name': 'Lesson kit',
                'verbose_name_plural': 'Lesson kits',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('instructor_note', models.TextField(blank=True, help_text='Discussion prompt or transition text before this entry')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path_steps', to='nomoar.historicalevent')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='nomoar.learningpath')),
            ],
            options={
                'verbose_name': 'Learning path step',
                'verbose_name_plural': 'Learning path steps',
                'ordering': ['path', 'order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('path', 'event'), name='nomoar_learningpathstep_path_event_uniq')],
            },
        ),
        migrations.RunPython(create_engagement_config, migrations.RunPython.noop),
    ]
