# Generated by Django 5.2 on 2026-03-21 21:12

from django.db import migrations, models


def seed_start_here(apps, schema_editor):
    LearningPath = apps.get_model('nomoar', 'LearningPath')
    EngagementConfig = apps.get_model('nomoar', 'EngagementConfig')
    paths = list(LearningPath.objects.filter(is_published=True).order_by('order', 'title')[:3])
    for i, p in enumerate(paths):
        p.show_on_start_here = True
        p.start_here_order = i
        p.save(update_fields=['show_on_start_here', 'start_here_order'])
    ec = EngagementConfig.objects.order_by('pk').first()
    if ec and not (ec.start_here_map_query or '').strip():
        ec.start_here_map_query = 'year_from=2020&year_to=2026&type=policy'
        ec.save(update_fields=['start_here_map_query'])


class Migration(migrations.Migration):

    dependencies = [
        ('nomoar', '0010_content_engagement_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementconfig',
            name='start_here_map_query',
            field=models.CharField(blank=True, help_text='Query string for the “Start here” map link, e.g. year_from=2020&year_to=2026&type=policy', max_length=500),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='related_terms',
            field=models.ManyToManyField(blank=True, help_text='Cross-links to other glossary entries', related_name='related_from_terms', to='nomoar.glossaryterm'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='show_on_start_here',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured on the “Start here” page (up to ~3 paths shown by order)'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='start_here_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on Start here'),
        ),
        migrations.RunPython(seed_start_here, migrations.RunPython.noop),
    ]
