# Generated by Django 6.0.3 on 2026-05-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("htac", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conceptcode",
            new_name="htac_concep_conditi_e78b6d_idx",
            old_name="htac_cc_condition_domain_idx",
        ),
        migrations.RenameIndex(
            model_name="conceptcode",
            new_name="htac_concep_concept_7193e5_idx",
            old_name="htac_cc_concept_vocab_idx",
        ),
        migrations.RenameIndex(
            model_name="conditionoccurrence",
            new_name="htac_condit_person__a0b4ee_idx",
            old_name="htac_cond_person_concept_idx",
        ),
        migrations.RenameIndex(
            model_name="conditionoccurrence",
            new_name="htac_condit_health__dc2a35_idx",
            old_name="htac_cond_site_concept_idx",
        ),
        migrations.RenameIndex(
            model_name="conditionoccurrence",
            new_name="htac_condit_conditi_3f2858_idx",
            old_name="htac_cond_concept_date_idx",
        ),
        migrations.RenameIndex(
            model_name="dataqualityreport",
            new_name="htac_dataqu_health__ea0984_idx",
            old_name="htac_dqr_site_date_idx",
        ),
        migrations.RenameIndex(
            model_name="deduplicatedroster",
            new_name="htac_dedupl_canonic_10608d_idx",
            old_name="htac_roster_site_idx",
        ),
        migrations.RenameIndex(
            model_name="deduplicatedroster",
            new_name="htac_dedupl_medicai_ac0e48_idx",
            old_name="htac_roster_medicaid_idx",
        ),
        migrations.RenameIndex(
            model_name="deduplicatedroster",
            new_name="htac_dedupl_homeles_ddb1aa_idx",
            old_name="htac_roster_homeless_idx",
        ),
        migrations.RenameIndex(
            model_name="deduplicatedroster",
            new_name="htac_dedupl_jail_fl_fb02d3_idx",
            old_name="htac_roster_jail_idx",
        ),
        migrations.RenameIndex(
            model_name="deduplicatedroster",
            new_name="htac_dedupl_prison__bda745_idx",
            old_name="htac_roster_prison_idx",
        ),
        migrations.RenameIndex(
            model_name="deduplicatedroster",
            new_name="htac_dedupl_decease_692ac4_idx",
            old_name="htac_roster_deceased_idx",
        ),
        migrations.RenameIndex(
            model_name="deduplicatedroster",
            new_name="htac_dedupl_roster__4b0029_idx",
            old_name="htac_roster_version_idx",
        ),
        migrations.RenameIndex(
            model_name="docrecord",
            new_name="htac_docrec_token_h_9e12c3_idx",
            old_name="htac_doc_token_type_idx",
        ),
        migrations.RenameIndex(
            model_name="drugexposure",
            new_name="htac_drugex_person__73d17c_idx",
            old_name="htac_drug_person_concept_idx",
        ),
        migrations.RenameIndex(
            model_name="drugexposure",
            new_name="htac_drugex_health__776436_idx",
            old_name="htac_drug_site_concept_idx",
        ),
        migrations.RenameIndex(
            model_name="drugexposure",
            new_name="htac_drugex_drug_co_712981_idx",
            old_name="htac_drug_concept_date_idx",
        ),
        migrations.RenameIndex(
            model_name="hmisrecord",
            new_name="htac_hmisre_token_h_c05bde_idx",
            old_name="htac_hmis_token_date_idx",
        ),
        migrations.RenameIndex(
            model_name="measurement",
            new_name="htac_measur_person__5b52cc_idx",
            old_name="htac_meas_person_concept_idx",
        ),
        migrations.RenameIndex(
            model_name="measurement",
            new_name="htac_measur_health__367c15_idx",
            old_name="htac_meas_site_concept_idx",
        ),
        migrations.RenameIndex(
            model_name="measurement",
            new_name="htac_measur_measure_3f3086_idx",
            old_name="htac_meas_concept_date_idx",
        ),
        migrations.RenameIndex(
            model_name="medicaidenrollment",
            new_name="htac_medica_token_h_dfe291_idx",
            old_name="htac_medicaid_token_date_idx",
        ),
        migrations.RenameIndex(
            model_name="miicrecord",
            new_name="htac_miicre_token_h_23ebf3_idx",
            old_name="htac_miic_token_type_idx",
        ),
        migrations.RenameIndex(
            model_name="observation",
            new_name="htac_observ_person__14b39b_idx",
            old_name="htac_obs_person_concept_idx",
        ),
        migrations.RenameIndex(
            model_name="observation",
            new_name="htac_observ_health__24c5b5_idx",
            old_name="htac_obs_site_concept_idx",
        ),
        migrations.RenameIndex(
            model_name="observation",
            new_name="htac_observ_observa_0de898_idx",
            old_name="htac_obs_concept_date_idx",
        ),
        migrations.RenameIndex(
            model_name="person",
            new_name="htac_person_health__490572_idx",
            old_name="htac_person_site_val_idx",
        ),
        migrations.RenameIndex(
            model_name="prevalenceestimate",
            new_name="htac_preval_study_r_b9711e_idx",
            old_name="htac_prev_run_cond_strat_idx",
        ),
        migrations.RenameIndex(
            model_name="prevalenceestimate",
            new_name="htac_preval_geo_lev_897b32_idx",
            old_name="htac_prev_geo_idx",
        ),
        migrations.RenameIndex(
            model_name="prevalenceestimate",
            new_name="htac_preval_conditi_da7a3b_idx",
            old_name="htac_prev_cond_site_idx",
        ),
        migrations.RenameIndex(
            model_name="prevalenceestimate",
            new_name="htac_preval_study_r_295dc7_idx",
            old_name="htac_prev_run_suppressed_idx",
        ),
        migrations.RenameIndex(
            model_name="visitoccurrence",
            new_name="htac_visito_person__218dde_idx",
            old_name="htac_visit_person_date_idx",
        ),
        migrations.RenameIndex(
            model_name="visitoccurrence",
            new_name="htac_visito_health__aa8a1e_idx",
            old_name="htac_visit_site_date_idx",
        ),
        migrations.AddField(
            model_name="drugexposure",
            name="drug_type_concept_id",
            field=models.IntegerField(default=32817),
        ),
        migrations.AddField(
            model_name="measurement",
            name="measurement_type_concept_id",
            field=models.IntegerField(default=44818702),
        ),
        migrations.AddField(
            model_name="observation",
            name="observation_type_concept_id",
            field=models.IntegerField(default=38000280),
        ),
        migrations.AddField(
            model_name="observation",
            name="unit_concept_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="value_as_number",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="conceptcode",
            name="vocabulary_id",
            field=models.CharField(
                choices=[
                    ("ICD10CM", "ICD-10-CM"),
                    ("SNOMED", "SNOMED CT"),
                    ("RxNorm", "RxNorm"),
                    ("LOINC", "LOINC"),
                    ("NDC", "NDC"),
                    ("CPT4", "CPT-4"),
                    ("HCPCS", "HCPCS"),
                    ("ICD10PCS", "ICD-10-PCS"),
                    ("RxNorm Extension", "RxNorm Extension"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prevalenceestimate",
            name="prevalence_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Cases per 10,000 persons. Null when is_suppressed is True.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
