# Generated by Django 5.2 on 2026-05-14 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htac', '0002_add_omop_type_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('total_patients_raw', models.IntegerField(default=0)),
                ('total_patients_deduplicated', models.IntegerField(default=0)),
                ('cross_site_matches', models.IntegerField(default=0)),
                ('homeless_flagged', models.IntegerField(default=0)),
                ('incarcerated_flagged', models.IntegerField(default=0)),
                ('medicaid_flagged', models.IntegerField(default=0)),
                ('total_estimates_generated', models.IntegerField(default=0)),
                ('total_estimates_suppressed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('narrative_headline', models.CharField(blank=True, max_length=200)),
                ('narrative_body', models.TextField(blank=True)),
                ('technical_detail', models.TextField(blank=True)),
                ('metric_label', models.CharField(blank=True, max_length=100)),
                ('metric_value', models.CharField(blank=True, max_length=100)),
                ('site_data', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='htac.pipelinerun')),
            ],
            options={
                'ordering': ['step_number'],
                'constraints': [models.UniqueConstraint(fields=('run', 'step_number'), name='htac_pipelinestep_unique_run_step_number')],
            },
        ),
    ]
