from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone

from dream_blue.digest_context import (
    build_operations_calendar_markdown,
    get_latest_completed_grantscout_run,
)
from dream_blue.grantscout_agent import GrantScoutAgentError, run_grantscout_agent
from dream_blue.grantscout_reports import build_agent_snapshot, build_compiled_report
from dream_blue.models import (
    GrantScoutDriftEntry,
    GrantScoutDriftType,
    GrantScoutOpportunity,
    GrantScoutRun,
    GrantScoutRunStatus,
)


class Command(BaseCommand):
    help = (
        'Run the GrantScout LLM agent (OpenAI or Perplexity), save a completed run '
        'and opportunities, optional drift vs previous completed run.'
    )

    def add_arguments(self, parser):
        parser.add_argument(
            '--period',
            type=str,
            default='',
            help='Period label e.g. 2026-04 (default: current UTC year-month)',
        )
        parser.add_argument(
            '--dry-run',
            action='store_true',
            help='Call the LLM and print summary counts; do not write to the database.',
        )
        parser.add_argument(
            '--no-drift',
            action='store_true',
            help='Do not create GrantScoutDriftEntry rows vs previous run.',
        )
        parser.add_argument(
            '--skip-url-check',
            action='store_true',
            help='Keep opportunities without HTTP GET checks (faster; may include 404 links).',
        )

    def handle(self, *args, **options):
        period = (options['period'] or '').strip()
        if not period:
            period = timezone.now().strftime('%Y-%m')

        validate_urls = not options['skip_url_check']
        try:
            payload = run_grantscout_agent(validate_urls=validate_urls)
        except GrantScoutAgentError as e:
            raise CommandError(str(e)) from e

        n = len(payload['opportunities'])
        cov = payload['coverage_summary']
        cov_preview = f'{cov[:200]}…' if len(cov) > 200 else cov
        self.stdout.write(
            self.style.SUCCESS(f'Agent returned {n} opportunity(ies); coverage: {cov_preview}')
        )

        if options['dry_run']:
            self.stdout.write(self.style.WARNING('Dry run: no database changes.'))
            return

        prev = get_latest_completed_grantscout_run()

        snapshot = build_agent_snapshot(payload)
        compiled = build_compiled_report(payload).strip()
        calendar_md = build_operations_calendar_markdown()
        if calendar_md:
            compiled = f'{compiled}\n\n{calendar_md}'

        with transaction.atomic():
            run = GrantScoutRun.objects.create(
                period_label=period[:32],
                status=GrantScoutRunStatus.DRAFT,
                previous_run=prev,
                search_query_log=payload['search_queries'],
                coverage_summary=payload['coverage_summary'],
                compiled_report=compiled,
                agent_snapshot=snapshot,
                notes='Generated by grantscout_run_agent',
            )
            opps = []
            for o in payload['opportunities']:
                opps.append(
                    GrantScoutOpportunity(
                        run=run,
                        category=o['category'],
                        opportunity_type=o['opportunity_type'],
                        eligibility=o['eligibility'],
                        deadline=o['deadline'] or None,
                        summary=o['summary'],
                        action_recommended=o['action_recommended'],
                        source_url=o['source_url'],
                        priority_score=o['priority_score'],
                        dedupe_key=o['dedupe_key'],
                        source_url_check_passed=o.get('source_url_check_passed'),
                    )
                )
            GrantScoutOpportunity.objects.bulk_create(opps)
            run.status = GrantScoutRunStatus.COMPLETED
            run.save(update_fields=['status', 'updated_at'])

            if not options['no_drift'] and prev:
                old_by_key = {
                    o.dedupe_key: o
                    for o in prev.opportunities.all()
                    if o.dedupe_key
                }
                new_by_key = {
                    o.dedupe_key: o
                    for o in GrantScoutOpportunity.objects.filter(run=run).order_by('id')
                    if o.dedupe_key
                }
                old_keys = set(old_by_key)
                new_keys = set(new_by_key)

                for key in new_keys - old_keys:
                    GrantScoutDriftEntry.objects.create(
                        run=run,
                        drift_type=GrantScoutDriftType.NEW,
                        opportunity=new_by_key[key],
                        summary=f'New: {new_by_key[key].summary[:200]}',
                    )
                for key in old_keys - new_keys:
                    po = old_by_key[key]
                    GrantScoutDriftEntry.objects.create(
                        run=run,
                        drift_type=GrantScoutDriftType.REMOVED,
                        previous_opportunity=po,
                        summary=f'Removed since last run: {po.summary[:200]}',
                    )

        self.stdout.write(
            self.style.SUCCESS(
                f'Created GrantScout run id={run.id} period={run.period_label} with {n} opportunities.'
            )
        )
