# Generated by Django 5.2 on 2025-12-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', unique=True)),
                ('description', models.TextField(help_text='Description shown on the homepage')),
                ('icon', models.CharField(default='📱', help_text='Emoji icon', max_length=10)),
                ('url', models.CharField(help_text='URL path to the app (e.g., /apps/cards/)', max_length=200)),
                ('cover_image', models.CharField(blank=True, help_text='Path to cover image (e.g., erickvale/images/king_and_death.avif)', max_length=200, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text="List of features (e.g., ['Feature 1', 'Feature 2'])")),
                ('month', models.CharField(help_text="Month/year (e.g., 'January 2025')", max_length=50)),
                ('is_current_month', models.BooleanField(default=False, help_text="Is this the current month's featured app?")),
                ('is_published', models.BooleanField(default=True, help_text='Show this app on the homepage')),
                ('order', models.IntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Featured App',
                'verbose_name_plural': 'Featured Apps',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
