# Generated by Django 5.2 on 2026-07-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erickvale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredapp',
            name='is_current_month',
        ),
        migrations.RemoveField(
            model_name='featuredapp',
            name='month',
        ),
        migrations.AddField(
            model_name='featuredapp',
            name='category',
            field=models.CharField(choices=[('data', 'Data & Public Health'), ('games', 'Games & Play'), ('tools', 'Tools & Utilities'), ('research', 'Writing & Research')], default='tools', max_length=20),
        ),
        migrations.AddField(
            model_name='featuredapp',
            name='featured_size',
            field=models.CharField(choices=[('large', 'Large tile'), ('normal', 'Normal tile')], default='normal', help_text='Large tiles get a bigger spot in the bento grid — reserve for flagship projects.', max_length=10),
        ),
        migrations.AddField(
            model_name='featuredapp',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Short one-line hook shown on the project tile', max_length=140),
        ),
    ]
