# Generated by Django 5.2 on 2026-07-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erickvale', '0002_remove_featuredapp_is_current_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredapp',
            name='category',
            field=models.CharField(choices=[('data', 'Data & Analytics'), ('games', 'Games & Play'), ('tools', 'Tools & Utilities'), ('research', 'Writing & Research')], default='tools', max_length=20),
        ),
    ]
