# Generated by Django 5.2 on 2026-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erickvale', '0003_alter_featuredapp_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredapp',
            name='featured_size',
            field=models.CharField(choices=[('large', 'Large tile'), ('normal', 'Normal tile')], default='normal', help_text='Large tiles get a bigger spot in the bento grid. Reserve for flagship projects.', max_length=10),
        ),
    ]
