# Generated by Django 5.2 on 2026-01-26 16:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('duplicate_detection', 'Duplicate Detection'), ('anomaly_detection', 'Anomaly Detection'), ('vendor_analysis', 'Vendor Analysis'), ('department_comparison', 'Department Comparison'), ('contract_analysis', 'Contract Analysis'), ('temporal_analysis', 'Temporal Analysis'), ('full_analysis', 'Full Analysis')], max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('flags_created', models.IntegerField(default=0)),
                ('transactions_analyzed', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('run_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='fraud_detection.budgetcategory')),
            ],
            options={
                'verbose_name_plural': 'Budget Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='fraud_detection.department')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='fraud_detec_name_d8ce63_idx'), models.Index(fields=['registration_number'], name='fraud_detec_registr_42ffd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='approved', max_length=20)),
                ('fiscal_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('contract_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fraud_detection.budgetcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fraud_detection.department')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fraud_detection.vendor')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('duplicate_payment', 'Duplicate Payment'), ('anomaly', 'Anomaly'), ('vendor_pattern', 'Suspicious Vendor Pattern'), ('round_number', 'Round Number Payment'), ('end_of_year_spike', 'End of Year Spending Spike'), ('contract_discrepancy', 'Contract Price Discrepancy'), ('employee_overlap', 'Employee/Vendor Overlap'), ('unusual_pattern', 'Unusual Spending Pattern')], max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('contracts', models.ManyToManyField(blank=True, related_name='fraud_flags', to='fraud_detection.contract')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
                ('transactions', models.ManyToManyField(blank=True, related_name='fraud_flags', to='fraud_detection.transaction')),
                ('vendors', models.ManyToManyField(blank=True, related_name='fraud_flags', to='fraud_detection.vendor')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='fraud_detection.vendor'),
        ),
        migrations.CreateModel(
            name='BudgetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(db_index=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_records', to='fraud_detection.budgetcategory')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_records', to='fraud_detection.department')),
            ],
            options={
                'ordering': ['-fiscal_year', 'department'],
                'indexes': [models.Index(fields=['fiscal_year', 'department'], name='fraud_detec_fiscal__2dc656_idx')],
                'unique_together': {('department', 'category', 'fiscal_year')},
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-date'], name='fraud_detec_date_8ea07a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['vendor', 'date'], name='fraud_detec_vendor__cdc806_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['department', 'date'], name='fraud_detec_departm_bb050e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['amount'], name='fraud_detec_amount_e1d7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fiscal_year'], name='fraud_detec_fiscal__405ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudflag',
            index=models.Index(fields=['-detected_at'], name='fraud_detec_detecte_3e3291_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudflag',
            index=models.Index(fields=['risk_level', 'status'], name='fraud_detec_risk_le_0918ab_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudflag',
            index=models.Index(fields=['flag_type'], name='fraud_detec_flag_ty_e16169_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['vendor', 'start_date'], name='fraud_detec_vendor__f7b762_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['department', 'start_date'], name='fraud_detec_departm_2add9d_idx'),
        ),
    ]
