# Generated by Django 5.2 on 2026-01-26 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('random', 'Random Selection'), ('risk_based', 'Risk-Based Selection'), ('scheduled', 'Scheduled Audit'), ('manual', 'Manual Audit')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('risk_threshold', models.DecimalField(blank=True, decimal_places=4, help_text='Minimum risk score for selection', max_digits=5, null=True)),
                ('random_percentage', models.IntegerField(default=5, help_text='Percentage of transactions to randomly audit')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_audits', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_audits', to=settings.AUTH_USER_MODEL)),
                ('contracts', models.ManyToManyField(blank=True, related_name='audits', to='fraud_detection.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audits', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='audits', to='fraud_detection.department')),
                ('transactions', models.ManyToManyField(blank=True, related_name='audits', to='fraud_detection.transaction')),
                ('vendors', models.ManyToManyField(blank=True, related_name='audits', to='fraud_detection.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HumanIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('review', 'Review Required'), ('approval', 'Approval Required'), ('escalation', 'Escalation'), ('investigation', 'Investigation'), ('resolution', 'Resolution')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_required', models.TextField(help_text='What action needs to be taken')),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, help_text='User who must approve', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_interventions', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL)),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='fraud_detection.audit')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interventions', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_interventions', to=settings.AUTH_USER_MODEL)),
                ('fraud_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='fraud_detection.fraudflag')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_interventions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='fraud_detection.transaction')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xgboost_score', models.DecimalField(blank=True, decimal_places=4, help_text='XGBoost fraud probability (0-1)', max_digits=5, null=True)),
                ('pyod_anomaly_score', models.DecimalField(blank=True, decimal_places=4, help_text='PyOD anomaly score', max_digits=10, null=True)),
                ('ensemble_score', models.DecimalField(blank=True, decimal_places=4, help_text='Combined ensemble score (0-1)', max_digits=5, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(blank=True, help_text='Version of ML model used', max_length=50)),
                ('features_used', models.JSONField(blank=True, default=dict, help_text='Features used in calculation')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='fraud_detection.transaction')),
            ],
            options={
                'ordering': ['-ensemble_score'],
            },
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['status', 'scheduled_date'], name='fraud_detec_status_4462d8_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['assigned_to', 'status'], name='fraud_detec_assigne_6abe32_idx'),
        ),
        migrations.AddIndex(
            model_name='humanintervention',
            index=models.Index(fields=['status', 'priority'], name='fraud_detec_status_7805e6_idx'),
        ),
        migrations.AddIndex(
            model_name='humanintervention',
            index=models.Index(fields=['assigned_to', 'status'], name='fraud_detec_assigne_bfc4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='humanintervention',
            index=models.Index(fields=['due_date'], name='fraud_detec_due_dat_313342_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['-ensemble_score'], name='fraud_detec_ensembl_b27179_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['risk_level'], name='fraud_detec_risk_le_c26eba_idx'),
        ),
    ]
