# Generated by Django 5.2 on 2026-01-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tanzania Mango Market Simulation', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation_data', models.JSONField(default=dict, help_text='Complete simulation results')),
                ('season', models.CharField(default='Peak Season', max_length=50)),
                ('region', models.CharField(default='Tanzania', max_length=100)),
            ],
            options={
                'verbose_name': 'Market Simulation',
                'verbose_name_plural': 'Market Simulations',
                'ordering': ['-created_at'],
            },
        ),
    ]
