# Generated by Django 5.2 on 2026-01-10 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsimulation',
            name='avg_dried_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketsimulation',
            name='avg_fresh_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketsimulation',
            name='best_strategy',
            field=models.CharField(blank=True, help_text='Fresh, Dried, or Hybrid', max_length=20),
        ),
        migrations.AddField(
            model_name='marketsimulation',
            name='dried_net_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketsimulation',
            name='fresh_net_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketsimulation',
            name='hybrid_net_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketsimulation',
            name='is_saved',
            field=models.BooleanField(default=True, help_text='Whether this simulation should be kept for historical reference'),
        ),
        migrations.AddField(
            model_name='marketsimulation',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this simulation'),
        ),
        migrations.AddField(
            model_name='marketsimulation',
            name='quantity_kg',
            field=models.IntegerField(default=1000, help_text='Quantity in kg', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='marketsimulation',
            name='simulation_days',
            field=models.IntegerField(default=30, help_text='Number of days simulated', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='marketsimulation',
            name='name',
            field=models.CharField(blank=True, default='Tanzania Mango Market Simulation', max_length=200),
        ),
        migrations.AddIndex(
            model_name='marketsimulation',
            index=models.Index(fields=['-created_at'], name='mango_marke_created_e2170b_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsimulation',
            index=models.Index(fields=['season', 'region'], name='mango_marke_season_d816f7_idx'),
        ),
    ]
