# Generated by Django 5.2 on 2026-04-05 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Raw capture text')),
                ('title', models.CharField(blank=True, help_text='Short label from AI or you', max_length=200)),
                ('category_label', models.CharField(blank=True, help_text='Free-form area, e.g. Home, Work', max_length=120)),
                ('gtd_bucket', models.CharField(choices=[('next_action', 'Next action'), ('project', 'Project (multi-step)'), ('waiting', 'Waiting for'), ('someday', 'Someday / maybe'), ('reference', 'Reference'), ('calendar', 'Calendar / time-specific')], default='next_action', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Still to do'), ('waiting', 'Waiting'), ('done', 'Done')], db_index=True, default='open', max_length=16)),
                ('waiting_for', models.CharField(blank=True, help_text='Who / what you are waiting on', max_length=255)),
                ('calendar_date', models.DateField(blank=True, db_index=True, help_text='Day on the monthly calendar email', null=True)),
                ('archived', models.BooleanField(db_index=True, default=False, help_text='Hidden from active inbox when done; still on calendar as completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_payload', models.JSONField(blank=True, default=dict)),
                ('ai_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='braindump_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
