# Generated by Django 5.2 on 2026-04-05 17:42

from django.db import migrations, models


def forwards_calendar_hard(apps, schema_editor):
    CaptureItem = apps.get_model('braindump', 'CaptureItem')
    CaptureItem.objects.exclude(calendar_date__isnull=True).update(
        calendar_is_hard_date=True
    )


def backwards_calendar_hard(apps, schema_editor):
    CaptureItem = apps.get_model('braindump', 'CaptureItem')
    CaptureItem.objects.update(calendar_is_hard_date=False)


class Migration(migrations.Migration):

    dependencies = [
        ('braindump', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureitem',
            name='calendar_is_hard_date',
            field=models.BooleanField(db_index=True, default=False, help_text='True = belongs on calendar landscape; False = next-action list only'),
        ),
        migrations.AddField(
            model_name='captureitem',
            name='engagement',
            field=models.CharField(blank=True, choices=[('do_now', 'Do now'), ('defer', 'Defer (next action list)'), ('delegate', 'Delegate / waiting')], default='', help_text='Do now, defer, or delegate', max_length=16),
        ),
        migrations.AddField(
            model_name='captureitem',
            name='is_actionable',
            field=models.BooleanField(blank=True, help_text='Clarify: is this actionable? null = not yet processed', null=True),
        ),
        migrations.AddField(
            model_name='captureitem',
            name='is_project',
            field=models.BooleanField(default=False, help_text='True if multi-step outcome (project list)'),
        ),
        migrations.AddField(
            model_name='captureitem',
            name='next_action',
            field=models.TextField(blank=True, help_text='Concrete next physical step (Allen)'),
        ),
        migrations.AddField(
            model_name='captureitem',
            name='non_actionable_disposition',
            field=models.CharField(blank=True, choices=[('', '—'), ('trash', 'Trash'), ('someday', 'Someday / maybe'), ('reference', 'Reference')], default='', help_text='If not actionable: trash, someday, or reference', max_length=16),
        ),
        migrations.AddField(
            model_name='captureitem',
            name='two_minute_rule_suggested',
            field=models.BooleanField(default=False, help_text='AI thinks this may be a under-two-minute action'),
        ),
        migrations.AlterField(
            model_name='captureitem',
            name='calendar_date',
            field=models.DateField(blank=True, db_index=True, help_text='GTD: use only for time-specific actions (hard appointment/deadline). Generic next actions stay off the calendar.', null=True),
        ),
        migrations.RunPython(forwards_calendar_hard, backwards_calendar_hard),
    ]
