# Generated by Django 5.2 on 2026-04-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braindump', '0002_gtd_clarify_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureitem',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], db_index=True, default='normal', help_text='Relative importance / time pressure (AI + editable)', max_length=16),
        ),
        migrations.AlterField(
            model_name='captureitem',
            name='category_label',
            field=models.CharField(blank=True, help_text='Life/work area (AI + editable), e.g. Work, Health, Dream Blue', max_length=120),
        ),
    ]
