# Generated by Django 5.2 on 2026-04-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braindump', '0003_task_priority_and_ai_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureitem',
            name='category_label',
            field=models.CharField(blank=True, help_text='Work stream: MDH, Dream Blue, or Sioux Chef (auto from text on AI; editable)', max_length=120),
        ),
    ]
