# Generated by Django 5.2 on 2026-04-05 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braindump', '0004_category_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringCaptureRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(help_text='Text for each spawned capture (AI clarifies)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('pattern', models.CharField(choices=[('weekly', 'Every week (same weekday)'), ('every_n_weeks', 'Every N weeks from anchor date'), ('monthly_last', 'Last Mon/Tue/… of each month'), ('monthly_nth', 'Nth weekday of month (1st–4th)'), ('monthly_day', 'Same calendar day each month')], max_length=32)),
                ('weekday', models.SmallIntegerField(blank=True, help_text='0=Monday … 6=Sunday (required for weekly / N-weeks / monthly weekday patterns)', null=True)),
                ('interval_weeks', models.PositiveSmallIntegerField(default=2, help_text='For “every N weeks” only (e.g. 2 = biweekly)')),
                ('nth_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1–4 for “nth weekday” (e.g. 2 = second Tuesday)', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1–31 for “same day each month”', null=True)),
                ('anchor_date', models.DateField(help_text='Anchor: first due intent; every-N-weeks counts from here')),
                ('next_run_date', models.DateField(db_index=True)),
                ('last_spawned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='braindump_recurring_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run_date', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='captureitem',
            name='spawned_from_recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_items', to='braindump.recurringcapturerule'),
        ),
    ]
