# Generated by Django 5.2 on 2026-02-19 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Brief case summary for the detective')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_type', models.CharField(choices=[('eyewitness', 'Eyewitness Account'), ('911_call', '911 Call Transcript'), ('video_analysis', 'Video Footage Analysis'), ('physical_evidence', 'Physical Evidence Report'), ('witness_statement', 'Additional Witness Statement'), ('surveillance', 'Surveillance Summary')], max_length=30)),
                ('title', models.CharField(help_text='Short label for this clue', max_length=200)),
                ('content', models.TextField(help_text='The actual clue content (transcript, report, etc.)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of revelation (1 = first)')),
                ('is_reliable', models.BooleanField(default=True, help_text='False for red herrings / unreliable witness')),
                ('filter_hints', models.JSONField(blank=True, default=dict, help_text='Attributes this clue implies for filtering suspects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='arm_chair_detective.case')),
            ],
            options={
                'ordering': ['case', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Unknown')], db_index=True, max_length=1)),
                ('age_range', models.CharField(choices=[('teens', 'Teenager (13-19)'), ('twenties', '20s'), ('thirties', '30s'), ('forties', '40s'), ('fifties', '50s'), ('sixties_plus', '60+'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('hair_color', models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('blonde', 'Blonde'), ('red', 'Red'), ('gray', 'Gray/White'), ('bald', 'Bald'), ('dyed', 'Dyed/Unusual'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('eye_color', models.CharField(choices=[('brown', 'Brown'), ('blue', 'Blue'), ('green', 'Green'), ('hazel', 'Hazel'), ('gray', 'Gray'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('skin_tone', models.CharField(choices=[('fair', 'Fair/Pale'), ('medium', 'Medium'), ('olive', 'Olive'), ('brown', 'Brown'), ('dark', 'Dark'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('build', models.CharField(choices=[('slim', 'Slim'), ('average', 'Average'), ('athletic', 'Athletic'), ('heavy', 'Heavy'), ('obese', 'Obese'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('height_range', models.CharField(choices=[('short', 'Under 5\'6"'), ('medium', '5\'6" - 5\'11"'), ('tall', '6\' - 6\'4"'), ('very_tall', 'Over 6\'4"'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('accent_region', models.CharField(choices=[('local', 'Local/No accent'), ('southern', 'Southern US'), ('northeastern', 'Northeastern'), ('midwestern', 'Midwestern'), ('hispanic', 'Hispanic/Spanish'), ('british', 'British'), ('european', 'European'), ('asian', 'Asian'), ('other', 'Other/Unrecognized'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('pickup', 'Pickup Truck'), ('van', 'Van/Minivan'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('motorcycle', 'Motorcycle'), ('none', 'No vehicle/On foot'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('vehicle_color', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('silver', 'Silver/Gray'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('brown', 'Brown/Tan'), ('gold', 'Gold/Beige'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('distinguishing_features', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['gender', 'age_range', 'hair_color'], name='arm_chair_d_gender_fe48fe_idx'), models.Index(fields=['vehicle_type', 'vehicle_color'], name='arm_chair_d_vehicle_a97555_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_filters', models.JSONField(blank=True, default=dict)),
                ('clues_revealed_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='arm_chair_detective.case')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detective_sessions', to=settings.AUTH_USER_MODEL)),
                ('guessed_suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guesses', to='arm_chair_detective.suspect')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='perpetrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_as_perpetrator', to='arm_chair_detective.suspect'),
        ),
    ]
