# Generated by Django 5.2 on 2026-02-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm_chair_detective', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='unlock_after_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Clue only becomes available after this many hours into the case (timeline pressure)', null=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='occupation',
            field=models.CharField(choices=[('delivery_driver', 'Delivery/Courier Driver'), ('retail', 'Retail/Service'), ('construction', 'Construction/Trades'), ('office', 'Office/Professional'), ('healthcare', 'Healthcare'), ('unemployed', 'Unemployed'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='clue',
            name='clue_type',
            field=models.CharField(choices=[('eyewitness', 'Eyewitness Account'), ('911_call', '911 Call Transcript'), ('video_analysis', 'Video Footage Analysis'), ('physical_evidence', 'Physical Evidence Report'), ('witness_statement', 'Additional Witness Statement'), ('surveillance', 'Surveillance Summary'), ('license_plate', 'License Plate Fragment'), ('cell_tower', 'Cell Tower / Location Data'), ('financial', 'Financial Records'), ('social_media', 'Social Media / Digital Footprint'), ('employer_records', 'Employer / Employment Records'), ('statement_analysis', 'Statement / Linguistic Analysis'), ('audio_transcript', 'Audio Transcript')], max_length=30),
        ),
    ]
