# Generated by Django 5.2 on 2025-12-12 15:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('json_data', models.JSONField(blank=True, default=dict, help_text='Complete analysis data')),
                ('report_html', models.TextField(blank=True, help_text='Cached HTML report')),
                ('report_generated_at', models.DateTimeField(blank=True, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticalMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='literary_analysis.analysis')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytical_memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytical Memo',
                'verbose_name_plural': 'Analytical Memos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodebookTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('dhalgren', 'Dhalgren Specialized Analyzer'), ('divine_comedy', 'Divine Comedy Analyzer'), ('custom', 'Custom Codebook'), ('general', 'General Narrative Fiction')], default='custom', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='Share with other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codebooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Codebook Template',
                'verbose_name_plural': 'Codebook Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(help_text='Unique identifier like "URBAN_DECAY"', max_length=100)),
                ('code_type', models.CharField(choices=[('descriptive', 'Descriptive'), ('process', 'Process'), ('emotion', 'Emotion'), ('values', 'Values'), ('structure', 'Structure')], default='descriptive', max_length=20)),
                ('definition', models.TextField(help_text='What this code captures')),
                ('examples', models.JSONField(blank=True, default=list, help_text='Example applications')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('parent_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcodes', to='literary_analysis.code')),
                ('codebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='literary_analysis.codebooktemplate')),
            ],
            options={
                'verbose_name': 'Code',
                'verbose_name_plural': 'Codes',
                'ordering': ['codebook', 'order', 'code_name'],
                'unique_together': {('codebook', 'code_name')},
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='codebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='literary_analysis.codebooktemplate'),
        ),
        migrations.CreateModel(
            name='CodedSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('text_excerpt', models.TextField(help_text='The actual text segment')),
                ('location', models.CharField(blank=True, help_text='Descriptive location like "Page 45, Chapter 3"', max_length=200)),
                ('memo', models.TextField(blank=True, help_text='Analytical note about this segment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coded_segments', to='literary_analysis.analysis')),
                ('codes', models.ManyToManyField(related_name='segments', to='literary_analysis.code')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coded_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coded Segment',
                'verbose_name_plural': 'Coded Segments',
                'ordering': ['start_position'],
            },
        ),
        migrations.CreateModel(
            name='LiteraryWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=200)),
                ('text_file', models.FileField(upload_to='literary_texts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('text_length', models.IntegerField(default=0, help_text='Character count')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literary_works', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Literary Work',
                'verbose_name_plural': 'Literary Works',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='literary_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='literary_analysis.literarywork'),
        ),
        migrations.AlterUniqueTogether(
            name='analysis',
            unique_together={('literary_work', 'codebook', 'analyst')},
        ),
    ]
