# Generated by Django 5.2 on 2025-12-12 18:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literary_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmemo',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Analytical memo content with rich text editor'),
        ),
        migrations.AlterField(
            model_name='codedsegment',
            name='memo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Analytical note about this segment'),
        ),
    ]
