# Generated by Django 5.2 on 2026-04-03 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrantScoutRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_label', models.CharField(help_text='e.g. 2026-03 for March 2026', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('search_query_log', models.JSONField(blank=True, default=list, help_text='List of queries or steps performed (for audit)')),
                ('coverage_summary', models.TextField(blank=True, help_text='Short narrative of jurisdictions/topics covered')),
                ('notes', models.TextField(blank=True)),
                ('previous_run', models.ForeignKey(blank=True, help_text='Prior run used for drift comparison', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_runs', to='dream_blue.grantscoutrun')),
            ],
            options={
                'verbose_name': 'GrantScout run',
                'verbose_name_plural': 'GrantScout runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantScoutOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('grant', 'Grant'), ('tax_credit', 'Tax credit'), ('rebate', 'Rebate'), ('regulatory', 'Regulatory / compliance'), ('other', 'Other')], default='other', max_length=32)),
                ('opportunity_type', models.CharField(blank=True, help_text='Subtype label, e.g. DEED program name', max_length=128)),
                ('eligibility', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('tracking', 'Tracking'), ('applied', 'Applied'), ('closed', 'Closed'), ('expired', 'Expired')], default='new', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('action_recommended', models.TextField(blank=True)),
                ('source_url', models.URLField(max_length=500)),
                ('priority_score', models.IntegerField(default=0, help_text='Higher = more important for dashboard/digest')),
                ('dedupe_key', models.CharField(blank=True, db_index=True, help_text='Stable id across runs (e.g. hash of canonical URL)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='dream_blue.grantscoutrun')),
            ],
            options={
                'verbose_name': 'GrantScout opportunity',
                'verbose_name_plural': 'GrantScout opportunities',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantScoutDriftEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drift_type', models.CharField(choices=[('new', 'New vs previous run'), ('updated', 'Updated vs previous run'), ('removed', 'Removed since previous run')], max_length=20)),
                ('summary', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('opportunity', models.ForeignKey(blank=True, help_text='Current-run opportunity when new or updated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drift_entries', to='dream_blue.grantscoutopportunity')),
                ('previous_opportunity', models.ForeignKey(blank=True, help_text='Prior-run row for updated/removed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drift_entries_as_previous', to='dream_blue.grantscoutopportunity')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_entries', to='dream_blue.grantscoutrun')),
            ],
            options={
                'verbose_name': 'GrantScout drift entry',
                'verbose_name_plural': 'GrantScout drift entries',
                'ordering': ['drift_type', 'id'],
            },
        ),
    ]
