# Generated by Django 5.2 on 2026-04-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_blue', '0001_initial_grantscout_and_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantscoutrun',
            name='agent_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Full normalized agent payload (audit / re-import)'),
        ),
        migrations.AddField(
            model_name='grantscoutrun',
            name='compiled_report',
            field=models.TextField(blank=True, help_text='Full human-readable report (Markdown) generated when the agent runs'),
        ),
    ]
