# Generated by Django 5.2 on 2026-04-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_blue', '0002_grantscout_stored_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantscoutopportunity',
            name='source_url_check_passed',
            field=models.BooleanField(blank=True, help_text='True if HTTP check passed, False if check failed (link may still be useful), null if not checked', null=True),
        ),
    ]
