# Generated by Django 5.2 on 2026-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_blue', '0003_grantscout_source_url_check_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('bill', 'Bill / recurring payment'), ('lease', 'Lease / occupancy'), ('property_tax', 'Property tax'), ('insurance', 'Insurance'), ('license', 'License / permit'), ('loan', 'Loan / financing'), ('maintenance', 'Maintenance / capex'), ('other', 'Other')], default='other', max_length=32)),
                ('due_date', models.DateField(db_index=True, help_text='Primary date (e.g. bill due, tax deadline, lease end)')),
                ('end_date', models.DateField(blank=True, help_text='Optional range end (e.g. renewal window)', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional amount for cash-flow context', max_digits=14, null=True)),
                ('property_label', models.CharField(blank=True, help_text='Building, parcel, or entity label', max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business calendar event',
                'verbose_name_plural': 'Business calendar events',
                'ordering': ['due_date', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessKPIEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value_display', models.CharField(help_text='Plain text, e.g. 12.4%, $42k, 3 units', max_length=120)),
                ('detail', models.TextField(blank=True, help_text='Optional short note / definition')),
                ('period_hint', models.CharField(blank=True, help_text='e.g. YTD 2026, Q1, trailing 12 mo', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business KPI',
                'verbose_name_plural': 'Business KPIs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable id, e.g. liquidity-summary, portfolio-outlook', max_length=64, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(help_text='Plain text or light Markdown; rendered with line breaks in email')),
                ('source', models.CharField(choices=[('manual', 'Manual / admin'), ('agent', 'Generated (future agent)')], default='manual', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business report section',
                'verbose_name_plural': 'Business report sections',
                'ordering': ['sort_order', 'slug'],
            },
        ),
    ]
