# Generated by Django 5.2 on 2026-04-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_blue', '0005_seed_property_leases_and_income_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscalendarevent',
            name='account_reference',
            field=models.CharField(blank=True, help_text='Utility account #, loan #, or similar', max_length=120),
        ),
        migrations.AddField(
            model_name='businesscalendarevent',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Vendor / contact for this expense (phone, company name)', max_length=255),
        ),
        migrations.AddField(
            model_name='businesscalendarevent',
            name='interest_rate_annual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate % for loans (e.g. 7.50 for 7.5%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='businesscalendarevent',
            name='event_type',
            field=models.CharField(choices=[('bill', 'Bill / recurring payment'), ('lease', 'Lease / occupancy'), ('property_tax', 'Property tax'), ('insurance', 'Insurance'), ('license', 'License / permit'), ('loan', 'Loan / financing'), ('maintenance', 'Maintenance / capex'), ('utility', 'Utility (electric, gas, etc.)'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
