# Generated by Django 5.2 on 2026-04-03 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_blue', '0015_beltrami_500_sf_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBooksReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(help_text='e.g. Mar 2026 or FY2026-Q1', max_length=64)),
                ('monthly_rent_income_books', models.DecimalField(blank=True, decimal_places=2, help_text='Rent income per books for the period (monthly equivalent)', max_digits=14, null=True)),
                ('monthly_operating_expense_books', models.DecimalField(blank=True, decimal_places=2, help_text='Operating expense per books (excl. debt principal if you separate it)', max_digits=14, null=True)),
                ('variance_notes', models.TextField(blank=True, help_text='Explain timing, accrual, or one-offs driving variance vs calendar')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Books reconciliation',
                'verbose_name_plural': 'Books reconciliations',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.AddField(
            model_name='businesscalendarevent',
            name='lease_document_url',
            field=models.URLField(blank=True, help_text='Lease abstract, LOI, or PDF link (leases); audit trail', max_length=500),
        ),
        migrations.AddField(
            model_name='businesscalendarevent',
            name='rent_basis',
            field=models.CharField(choices=[('gross', 'Gross (all-in rent)'), ('nnn', 'NNN / net (base + pass-throughs)'), ('unknown', 'Unknown / mixed')], default='unknown', help_text='Lease rows: gross vs NNN for honest comparison to suggested gross asks', max_length=16),
        ),
        migrations.AddField(
            model_name='businesscalendarevent',
            name='rent_basis_note',
            field=models.TextField(blank=True, help_text='e.g. “NNN + CAM ~$4/sf” or “Gross incl. utilities”'),
        ),
        migrations.AddField(
            model_name='grantscoutopportunity',
            name='topic_tags',
            field=models.JSONField(blank=True, default=list, help_text='Lowercase labels, e.g. ["bemidji","retail","energy"] — digest can filter by GRANTSCOUT_DIGEST_TOPIC_TAGS'),
        ),
        migrations.AddField(
            model_name='leasecompresearchrun',
            name='previous_run',
            field=models.ForeignKey(blank=True, help_text='Prior completed run used for report diff in digest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following_runs', to='dream_blue.leasecompresearchrun'),
        ),
        migrations.AddField(
            model_name='leasecompresearchrun',
            name='report_diff_summary',
            field=models.TextField(blank=True, help_text='Unified diff snippet vs previous_run (set when a new run is saved)'),
        ),
        migrations.AlterField(
            model_name='businesscalendarevent',
            name='reference_url',
            field=models.URLField(blank=True, help_text='Vendor link, portal, or secondary doc (utilities, loans, etc.)', max_length=500),
        ),
        migrations.AlterField(
            model_name='businesscalendarevent',
            name='square_footage',
            field=models.PositiveIntegerField(blank=True, help_text='Above-grade leasable sq ft (leases) — primary rent area; digest economics', null=True),
        ),
        migrations.CreateModel(
            name='LeaseRentRollChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('amount_before', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('square_footage_before', models.PositiveIntegerField(blank=True, null=True)),
                ('square_footage_after', models.PositiveIntegerField(blank=True, null=True)),
                ('square_footage_storage_before', models.PositiveIntegerField(blank=True, null=True)),
                ('square_footage_storage_after', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='admin', help_text='Where the change was captured', max_length=32)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_roll_changes', to='dream_blue.businesscalendarevent')),
            ],
            options={
                'verbose_name': 'Lease rent roll change',
                'verbose_name_plural': 'Lease rent roll changes',
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
