# Parallel branch from 0015: square_footage null/help_text only (often created on a
# server before pulling 0016_books). Merged in 0018 with the mainline chain.
# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_blue', '0015_beltrami_500_sf_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscalendarevent',
            name='square_footage',
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    'Above-grade leasable sq ft (leases) — primary rent area; digest economics'
                ),
                null=True,
            ),
        ),
    ]
