# Generated by Django 5.2 on 2026-04-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_blue', '0016_books_rent_basis_tags_lease_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscalendarevent',
            name='lease_pipeline_status',
            field=models.CharField(choices=[('not_tracked', 'Not tracking'), ('priced', 'Priced'), ('listed', 'Listed'), ('toured', 'Toured'), ('loi_out', 'LOI out'), ('out_for_signature', 'Out for signature'), ('leased_closed', 'Leased / closed')], default='not_tracked', help_text='Vacancy / renewal pipeline stage (staff command center + digest)', max_length=32),
        ),
        migrations.AddField(
            model_name='businesscalendarevent',
            name='vacancy_started',
            field=models.DateField(blank=True, db_index=True, help_text='Vacant lease rows: first day without rent — drives days vacant × $ impact sort', null=True),
        ),
    ]
