from django.urls import path

from .views import (
    AboutView,
    AdminDashboardView,
    DashboardRouterView,
    EmployeeDashboardView,
    FacetCreateView,
    FacetDeleteView,
    FacetUpdateView,
    LandingImageCreateView,
    LandingImageDeleteView,
    LandingImageListView,
    LandingImageUpdateView,
    PublicationCreateView,
    PublicationDeleteView,
    PublicationDetailView,
    PublicationLandingView,
    PublicationListView,
    PublicationUpdateView,
    TagCreateView,
    TagDeleteView,
    TagUpdateView,
    TaxonomyBrowserView,
    TaxonomyManageView,
    TopicGroupCreateView,
    TopicGroupDeleteView,
    TopicGroupUpdateView,
)

app_name = "mdh_publications"

urlpatterns = [
    path("", PublicationLandingView.as_view(), name="publication_landing"),
    path("about/", AboutView.as_view(), name="publication_about"),
    path("search/", PublicationListView.as_view(), name="publication_list"),
    path("landing/images/", LandingImageListView.as_view(), name="landing_image_list"),
    path("landing/images/add/", LandingImageCreateView.as_view(), name="landing_image_create"),
    path("landing/images/<int:pk>/edit/", LandingImageUpdateView.as_view(), name="landing_image_update"),
    path("landing/images/<int:pk>/delete/", LandingImageDeleteView.as_view(), name="landing_image_delete"),
    path("dashboard/", DashboardRouterView.as_view(), name="publication_dashboard"),
    path("dashboard/employee/", EmployeeDashboardView.as_view(), name="publication_employee_dashboard"),
    path("dashboard/admin/", AdminDashboardView.as_view(), name="publication_admin_dashboard"),
    path("taxonomy/", TaxonomyBrowserView.as_view(), name="publication_taxonomy"),
    path("taxonomy/manage/", TaxonomyManageView.as_view(), name="taxonomy_manage"),
    path("taxonomy/facets/new/", FacetCreateView.as_view(), name="facet_create"),
    path("taxonomy/facets/<int:pk>/edit/", FacetUpdateView.as_view(), name="facet_update"),
    path("taxonomy/facets/<int:pk>/delete/", FacetDeleteView.as_view(), name="facet_delete"),
    path("taxonomy/topic-groups/new/", TopicGroupCreateView.as_view(), name="topic_group_create"),
    path("taxonomy/topic-groups/<int:pk>/edit/", TopicGroupUpdateView.as_view(), name="topic_group_update"),
    path("taxonomy/topic-groups/<int:pk>/delete/", TopicGroupDeleteView.as_view(), name="topic_group_delete"),
    path("taxonomy/tags/new/", TagCreateView.as_view(), name="tag_create"),
    path("taxonomy/tags/<int:pk>/edit/", TagUpdateView.as_view(), name="tag_update"),
    path("taxonomy/tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", PublicationCreateView.as_view(), name="publication_create"),
    path("<slug:slug>/", PublicationDetailView.as_view(), name="publication_detail"),
    path("<slug:slug>/edit/", PublicationUpdateView.as_view(), name="publication_update"),
    path("<slug:slug>/delete/", PublicationDeleteView.as_view(), name="publication_delete"),
]