# Generated by Django 5.2 on 2025-12-05 14:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='card_sets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Card Set',
                'verbose_name_plural': 'Card Sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('card_type', models.CharField(choices=[('character', 'Character'), ('creature', 'Creature'), ('item', 'Item'), ('spell', 'Spell'), ('ability', 'Ability'), ('location', 'Location')], default='character', max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('card_image', models.ImageField(help_text='Main card image displayed prominently', upload_to='cards/')),
                ('card_image_alt', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('description', models.TextField(help_text='Card description/flavor text')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('health', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('attack', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('defense', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('speed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('intelligence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('strength', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('agility', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('mana_cost', models.IntegerField(default=0, help_text='Cost to play the card', validators=[django.core.validators.MinValueValidator(0)])),
                ('additional_stats', models.JSONField(blank=True, default=dict, help_text='Additional stats in JSON format')),
                ('abilities', models.TextField(blank=True, help_text='Card abilities or special skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within set')),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_maker.cardset')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['card_set', 'order', 'name'],
                'unique_together': {('card_set', 'slug')},
            },
        ),
    ]
