# Generated by Django 5.2 on 2025-12-05 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_maker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='agility',
        ),
        migrations.RemoveField(
            model_name='card',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='card',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='card',
            name='health',
        ),
        migrations.RemoveField(
            model_name='card',
            name='mana_cost',
        ),
        migrations.RemoveField(
            model_name='card',
            name='speed',
        ),
        migrations.AddField(
            model_name='card',
            name='charisma',
            field=models.IntegerField(default=0, help_text='CHR - Charisma stat', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='card',
            name='constitution',
            field=models.IntegerField(default=0, help_text='CON - Constitution stat', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='card',
            name='dexterity',
            field=models.IntegerField(default=0, help_text='DEX - Dexterity stat', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='intelligence',
            field=models.IntegerField(default=0, help_text='INT - Intelligence stat', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.IntegerField(default=1, help_text='Character level', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='strength',
            field=models.IntegerField(default=0, help_text='STR - Strength stat', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
