# Generated by Django 5.2 on 2025-12-07 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_maker', '0002_remove_card_agility_remove_card_attack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='album_label',
            field=models.CharField(blank=True, help_text='Album label for Kvale cards', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='collection',
            field=models.CharField(blank=True, help_text='Collection name for Kvale cards', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='edition',
            field=models.CharField(blank=True, help_text='Edition name for Kvale cards', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='energy',
            field=models.IntegerField(default=0, help_text='Energy stat for Kvale cards', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='card',
            name='power',
            field=models.IntegerField(default=0, help_text='Power stat for Kvale cards', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags as list of strings (e.g., ["nature", "science"])'),
        ),
        migrations.AddField(
            model_name='card',
            name='trigger',
            field=models.CharField(blank=True, help_text='Ability trigger text for Kvale cards', max_length=100),
        ),
    ]
