# Generated by Django 5.2 on 2026-03-04 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('side', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=10)),
                ('eco_code', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('move_sequence', models.JSONField(default=list, help_text='List of [white_move, black_move] pairs, e.g. [["e4","e5"],["Nf3","Nc6"]]')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(choices=[('concept', 'Concept'), ('drill', 'Drill'), ('quiz', 'Quiz')], max_length=20)),
                ('content', models.JSONField(default=dict, help_text='Key ideas, critical moves, common mistakes, tactical themes, quiz/drill config')),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='chess_trainer.opening')),
            ],
            options={
                'ordering': ['opening', 'order'],
                'unique_together': {('opening', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0, help_text='Score out of 100 for quiz/drill')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='chess_trainer.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chess_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_pct', models.FloatField(default=0.0, help_text='0-100')),
                ('streak', models.PositiveIntegerField(default=0, help_text='Days practiced in a row')),
                ('last_practiced', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='chess_trainer.opening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chess_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User stats',
                'unique_together': {('user', 'opening')},
            },
        ),
    ]
