# Generated by Django 5.2 on 2026-01-27 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('source_type', models.CharField(choices=[('rss', 'RSS'), ('atom', 'Atom'), ('other', 'Other')], default='rss', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_fetch_status', models.CharField(blank=True, max_length=50)),
                ('last_fetch_message', models.TextField(blank=True)),
                ('fetch_interval_hours', models.PositiveIntegerField(default=24, help_text='Hours between fetches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('articles_added', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='human_rights_archive.source')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text='e.g. human rights, constitutional, civil liberties', max_length=50)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['slug'], name='human_right_slug_2d830b_idx')],
            },
        ),
        migrations.AddField(
            model_name='source',
            name='default_tags',
            field=models.ManyToManyField(blank=True, related_name='sources_with_default', to='human_rights_archive.tag'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('url', models.URLField(db_index=True, max_length=2000, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Full text when stored')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_articles', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='human_rights_archive.source')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='human_rights_archive.tag')),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at'],
                'indexes': [models.Index(fields=['-published_at'], name='human_right_publish_4fa432_idx'), models.Index(fields=['source', '-published_at'], name='human_right_source__a48906_idx')],
            },
        ),
    ]
