# Generated by Django 5.2 on 2026-01-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_rights_archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for auto-tagging; if any appear in article title/summary/content, this tag is applied.'),
        ),
    ]
