# Generated by Django 5.2 on 2026-05-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_id', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('bureau', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('schedule', models.JSONField()),
                ('core_beliefs', models.TextField()),
                ('vision', models.TextField()),
                ('top_priorities', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'leader_id'],
                'unique_together': {('leader_id', 'date')},
            },
        ),
    ]
