# Generated by Django 5.2 on 2026-05-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_briefings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderbriefing',
            name='high_value_projects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leaderbriefing',
            name='relevant_news',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
