# Generated by Django 5.2 on 2026-02-02 23:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allminnesota_plans_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Business Plans',
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('contact_type', models.CharField(choices=[('VOLUNTEER', 'Volunteer'), ('DONOR', 'Donor'), ('TRIBAL_PARTNER', 'Tribal Partner'), ('MEDIA', 'Media'), ('COMMUNITY_MEMBER', 'Community Member'), ('ORGANIZATION', 'Organization')], default='COMMUNITY_MEMBER', max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allminnesota_contacts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DistributionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(choices=[('TWIN_CITIES', 'Twin Cities'), ('GREATER_MINNESOTA', 'Greater Minnesota')], default='TWIN_CITIES', max_length=30)),
                ('capacity', models.IntegerField(default=0, help_text='Max meals per distribution')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_sites', to='allminnesota.contact')),
            ],
            options={
                'verbose_name_plural': 'Distribution Sites',
                'ordering': ['region', 'site_name'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('unit', models.CharField(blank=True, help_text='e.g. meals, dollars, volunteers, sites', max_length=50)),
                ('category', models.CharField(choices=[('FUNDRAISING', 'Fundraising'), ('MEALS_DELIVERED', 'Meals Delivered'), ('VOLUNTEERS', 'Volunteers'), ('DISTRIBUTION', 'Distribution'), ('OUTREACH', 'Outreach')], default='MEALS_DELIVERED', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allminnesota_kpis_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'KPIs',
                'ordering': ['category', 'kpi_name'],
            },
        ),
        migrations.CreateModel(
            name='KPIUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to='allminnesota.kpi')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allminnesota_kpi_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'KPI Update History',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter'), ('TIKTOK', 'TikTok'), ('LINKEDIN', 'LinkedIn')], default='FACEBOOK', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('hashtags', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('related_event', models.CharField(blank=True, help_text='e.g. Keith Secola concert', max_length=200)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allminnesota_posts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Social Media Posts',
                'ordering': ['-scheduled_date', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='TODO', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('FUNDRAISING', 'Fundraising'), ('LOGISTICS', 'Logistics'), ('SOCIAL_MEDIA', 'Social Media'), ('OUTREACH', 'Outreach'), ('VOLUNTEER', 'Volunteer'), ('TRIBAL_PARTNERSHIP', 'Tribal Partnership'), ('EVENT', 'Event')], default='LOGISTICS', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allminnesota_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allminnesota_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('related_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='allminnesota.distributionsite')),
            ],
            options={
                'ordering': ['-due_date', 'priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='allminnesota.businessplan')),
            ],
            options={
                'verbose_name_plural': 'Plan Sections',
                'ordering': ['order', 'id'],
                'unique_together': {('plan', 'order')},
            },
        ),
    ]
