"""
Django settings for erickvale project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-**saixz-o2u6f^s4z$7o^rw0nt)&h1tzgq(##v6%ul+4)11^j+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='True') == 'True'

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'django.contrib.humanize',  # For intcomma filter
    'rest_framework',
    'ckeditor',
    'ckeditor_uploader',
    'erickvale',
    'emergency_preparedness',
    'blog',
    'card_maker',
    'literary_analysis',
    'personality_type_game',
    'mango_market',
    'activity_media',
    'fraud_detection',
    'human_rights_archive',
    'allminnesota',
    'arm_chair_detective',
    'chess_trainer',
    'nomoar',
    'dream_blue',
    'braindump',
]

# --- Brain dump (personal GTD capture; owner-only) ---
# Set username OR numeric user id of the single account that may use /apps/braindump/.
BRAINDUMP_OWNER_USERNAME = config('BRAINDUMP_OWNER_USERNAME', default='').strip()
BRAINDUMP_OWNER_USER_ID = config('BRAINDUMP_OWNER_USER_ID', default='').strip()
# braindump categorization: anthropic or perplexity (try the other if the first fails).
BRAINDUMP_LLM_PROVIDER = config('BRAINDUMP_LLM_PROVIDER', default='anthropic').strip().lower()
BRAINDUMP_ANTHROPIC_MODEL = config('BRAINDUMP_ANTHROPIC_MODEL', default='').strip()
BRAINDUMP_PERPLEXITY_MODEL = config('BRAINDUMP_PERPLEXITY_MODEL', default='').strip()
# Optional comma-separated override; default is the owner account's email.
BRAINDUMP_CALENDAR_EMAIL_RECIPIENTS = config(
    'BRAINDUMP_CALENDAR_EMAIL_RECIPIENTS',
    default='',
).strip()

# --- Dream Blue (internal BI / digests) ---
# Comma-separated recipient emails; no defaults — must be set in env for sends.
DREAM_BLUE_REPORT_RECIPIENTS = config('DREAM_BLUE_REPORT_RECIPIENTS', default='')
# How far ahead the email calendar lists active BusinessCalendarEvent rows (days from local today).
DREAM_BLUE_CALENDAR_LOOKAHEAD_DAYS = config(
    'DREAM_BLUE_CALENDAR_LOOKAHEAD_DAYS',
    default=120,
    cast=int,
)
# Absolute origin for digest links (no trailing slash), e.g. https://your.domain.org — required for working Prev/Next month links in email.
DREAM_BLUE_DIGEST_BASE_URL = config('DREAM_BLUE_DIGEST_BASE_URL', default='').strip()
# Digest + email: max rows in the "Money moves" rollover / vacancy slice (default 5).
DREAM_BLUE_MONEY_MOVES_LIMIT = config(
    'DREAM_BLUE_MONEY_MOVES_LIMIT',
    default=5,
    cast=int,
)

# Lease comparables agent (dream_blue_run_lease_comp_agent) — briefs injected into digest; override via env.
_DEFAULT_LEASE_COMP_REFERENCE = (
    'Our building at 401 Beltrami Ave, Bemidji, MN — benchmark for tracking local commercial '
    'trends and pricing. ~8,000 sq ft total, fire sprinklered, fully remodeled; divided into '
    'four ~2,000 sq ft leasable units (one with commercial kitchen capability). Primary tenancy is '
    'retail and service: salons, tattoo, restaurants, and similar small businesses — not only '
    'industrial/flex. Use comps to contextualize asking/target rent over time; not an appraisal.'
)
_DEFAULT_LEASE_COMP_SUBJECT = (
    'Four units ~2,000 sq ft each. In addition to close matches (retail / restaurant / service), '
    'the owner wants a **wide scan**: any **commercial** property **newly listed or recently '
    'marketed** (for lease or sale-as-lease context) in **Bemidji, Beltrami County, and '
    'north-central MN** — retail, office, medical, flex, warehouse, land with commercial angle, '
    'etc. Imperfect use-type matches are fine as market supply signals. Always label NNN vs gross '
    '(or unknown) and asking vs deal when known.'
)
DREAM_BLUE_LEASE_COMP_REFERENCE = config(
    'DREAM_BLUE_LEASE_COMP_REFERENCE', default=_DEFAULT_LEASE_COMP_REFERENCE
)
DREAM_BLUE_LEASE_COMP_SUBJECT = config(
    'DREAM_BLUE_LEASE_COMP_SUBJECT', default=_DEFAULT_LEASE_COMP_SUBJECT
)
# Lease economics block in digest: assumed economic vacancy (%) for breakeven gross rent math.
DREAM_BLUE_LEASE_ECONOMICS_VACANCY_PCT = config(
    'DREAM_BLUE_LEASE_ECONOMICS_VACANCY_PCT',
    default='8',
)
# Cap-rate band for digest lease economics (market-style implied value from trailing NOI).
DREAM_BLUE_CAP_RATE_BENCHMARK_LOW = config(
    'DREAM_BLUE_CAP_RATE_BENCHMARK_LOW',
    default='8',
)
DREAM_BLUE_CAP_RATE_BENCHMARK_HIGH = config(
    'DREAM_BLUE_CAP_RATE_BENCHMARK_HIGH',
    default='10',
)
# Digest suggested asking rents: gross $/sf/year on above-grade SF; lower tier for storage.
DREAM_BLUE_SUGGEST_RENT_PSF_YEAR_ABOVE = config(
    'DREAM_BLUE_SUGGEST_RENT_PSF_YEAR_ABOVE',
    default='9.5',
)
DREAM_BLUE_SUGGEST_RENT_PSF_YEAR_STORAGE = config(
    'DREAM_BLUE_SUGGEST_RENT_PSF_YEAR_STORAGE',
    default='2',
)
# Optional extra benchmark: asking/market $/sf/year (gross or NNN — say which in note below).
DREAM_BLUE_RENT_BENCHMARK_PSF_YEAR = config(
    'DREAM_BLUE_RENT_BENCHMARK_PSF_YEAR',
    default='',
).strip()
DREAM_BLUE_RENT_BENCHMARK_NOTE = config(
    'DREAM_BLUE_RENT_BENCHMARK_NOTE',
    default=(
        'Set DREAM_BLUE_RENT_BENCHMARK_PSF_YEAR from broker, Crexi/LoopNet ranges, or appraisal. '
        'State gross vs NNN in this note.'
    ),
)
# GrantScout digest: comma-separated lowercase tags; only opportunities whose topic_tags overlap are included (empty = show all).
GRANTSCOUT_DIGEST_TOPIC_TAGS = config(
    'GRANTSCOUT_DIGEST_TOPIC_TAGS',
    default='',
).strip()
RESEND_API_KEY = config('RESEND_API_KEY', default='')
RESEND_FROM_EMAIL = config('RESEND_FROM_EMAIL', default='')
RESEND_API_URL = config('RESEND_API_URL', default='https://api.resend.com/emails')

# GrantScout LLM agent (grantscout_run_agent). Use one provider; keys only via env.
GRANTSCOUT_LLM_PROVIDER = config('GRANTSCOUT_LLM_PROVIDER', default='openai').strip().lower()
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')
OPENAI_CHAT_COMPLETIONS_URL = config(
    'OPENAI_CHAT_COMPLETIONS_URL',
    default='https://api.openai.com/v1/chat/completions',
)
GRANTSCOUT_OPENAI_MODEL = config('GRANTSCOUT_OPENAI_MODEL', default='gpt-4o-mini')
PERPLEXITY_API_KEY = config('PERPLEXITY_API_KEY', default='')
PERPLEXITY_API_URL = config(
    'PERPLEXITY_API_URL',
    default='https://api.perplexity.ai/chat/completions',
)
GRANTSCOUT_PERPLEXITY_MODEL = config('GRANTSCOUT_PERPLEXITY_MODEL', default='sonar')

# Anthropic (Claude) for GrantScout when GRANTSCOUT_LLM_PROVIDER=anthropic
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='')
ANTHROPIC_API_URL = config(
    'ANTHROPIC_API_URL',
    default='https://api.anthropic.com/v1/messages',
)
ANTHROPIC_VERSION = config('ANTHROPIC_VERSION', default='2023-06-01')
GRANTSCOUT_ANTHROPIC_MODEL = config(
    'GRANTSCOUT_ANTHROPIC_MODEL',
    default='claude-sonnet-4-6',
)
GRANTSCOUT_ANTHROPIC_MAX_TOKENS = config(
    'GRANTSCOUT_ANTHROPIC_MAX_TOKENS',
    default=8192,
    cast=int,
)
# GrantScout: drop opportunities whose source_url returns 404/5xx (GET, browser-like UA).
GRANTSCOUT_VALIDATE_SOURCE_URLS = config(
    'GRANTSCOUT_VALIDATE_SOURCE_URLS',
    default='True',
) == 'True'
GRANTSCOUT_URL_CHECK_TIMEOUT = config(
    'GRANTSCOUT_URL_CHECK_TIMEOUT',
    default=15,
    cast=int,
)
GRANTSCOUT_URL_CHECK_DELAY_SEC = config(
    'GRANTSCOUT_URL_CHECK_DELAY_SEC',
    default=0.25,
    cast=float,
)

# Optional SMTP (same variables as Django; defaults match Django when unset).
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default='False') == 'True'
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='webmaster@localhost')
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.smtp.EmailBackend',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'erickvale.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'erickvale' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'nomoar.context_processors.nomoar_banner',
                'nomoar.context_processors.nomoar_engagement',
            ],
        },
    },
]

WSGI_APPLICATION = 'erickvale.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Build database config, only include password if it's set
db_config = {
    'ENGINE': 'django.db.backends.postgresql',
    'NAME': config('DB_NAME', default='erickvale'),
    'USER': config('DB_USER', default='postgres'),
    'HOST': config('DB_HOST', default='localhost'),
    'PORT': config('DB_PORT', default='5432'),
}

# Only add password if it's provided (not empty)
db_password = config('DB_PASSWORD', default='')
if db_password:
    db_config['PASSWORD'] = db_password

DATABASES = {
    'default': db_config
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'erickvale' / 'static',
]

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# NOMOAR: optional mailto for “report a correction” (shown under /apps/nomoar/)
NOMOAR_CORRECTIONS_EMAIL = config('NOMOAR_CORRECTIONS_EMAIL', default='')

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100
}

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 400,
        'width': '100%',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
            ['Image', 'Table', 'HorizontalRule'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize'],
        ],
        'toolbar': 'Custom',
        'extraPlugins': ','.join([
            'uploadimage',  # the upload image feature
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    },
    'blog': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['Link', 'Unlink'],
            ['Image', 'Table', 'HorizontalRule'],
            ['Styles', 'Format'],
            ['TextColor', 'BGColor'],
            ['RemoveFormat', 'Source'],
            ['Maximize'],
        ],
        'height': 500,
        'width': '100%',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
        'toolbarCanCollapse': True,
        'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}
